# Generated by Django 5.0.6 on 2024-07-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('lawyer', 'Lawyer'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
