# Generated by Django 5.0.6 on 2024-07-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0002_delete_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='Communication',
        ),
    ]
