# Generated by Django 5.0.6 on 2024-07-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='user',
        ),
    ]
