# Generated by Django 5.0.6 on 2024-07-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
